name: Image Push

on:
  push:
    branches:
      - main
  schedule:
    # Automatically Build on Sundays
    - cron:  '30 17 * * 0'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        target: ["", "slim", "alpine"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Image
        run: bash scripts/build_and_push.sh ${{ matrix.python_version }} ${{ matrix.target }}
        env:
          PYTHON_VERSION: ${{ matrix.python_version }}
          TARGET_TAG: ${{ matrix.target }}
