name: Image Push

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '30 17 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        image:
          - python_version: "latest"

          - python_version: "3.9"
          - python_version: "3.9"
            target: "slim"
          - python_version: "3.9"
            target: "alpine"

          - python_version: "3.8"
          - python_version: "3.8"
            target: "slim"
          - python_version: "3.8"
            target: "alpine"

          - python_version: "3.7"
          - python_version: "3.7"
            target: "slim"
          - python_version: "3.7"
            target: "alpine"

          - python_version: "3.6"
          - python_version: "3.6"
            target: "slim"
          - python_version: "3.6"
            target: "alpine"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Image
        run: bash scripts/build_and_push.sh ${{ matrix.image.python_version }} ${{ matrix.image.target }}
        env:
          PYTHON_VERSION: ${{ matrix.image.python_version }}
          TARGET_TAG: ${{ matrix.image.target }}
